category:
  category_id:
    type: Integer
    required: true
    parse:
      - Replace(",", ".")
      - ToFloat(2)
  name:
    type: String
    required: false
  last_update:
    type: Timestamptz
    required: true
actor:
  actor_id:
    type: Integer
    required: true
  first_name:
    type: String
    required: true
  last_name:
    type: String
    required: true
  last_update:
    type: Timestamptz
    required: true

address:
  address_id:
    type: Integer
    required: true
  address:
    type: String
    required: true
  address2:
    type: String
    required: false
  district:
    type: String
    required: true
  city_id:
    type: Integer
    required: true
  postal_code:
    type: String
    required: false 
  phone:
    type: String
    required: false  
  last_update:
    type: Timestamptz
    required: true

city:
  city_id:
    type: Integer
    required: true
  city:
    type: String
    required: true
  country_id:
    type: Integer
    required: true
  last_update:
    type: Timestamptz
    required: true

country:
  country_id:
    type: Integer
    required: true
  country:
    type: String
    required: true
  last_update:
    type: Timestamptz
    required: true

customer:
  customer_id:
    type: Integer
    required: true
  store_id:
    type: Integer
    required: true
  first_name:
    type: String
    required: true
  last_name:
    type: String
    required: true
  email:
    type: String
    required: false
  address_id:
    type: Integer
    required: true
  activebool:
    type: Boolean
    required: true
  create_date:
    type: Date
    required: true
    parse:
      - Replace('-', '/')
  last_update:
    type: Timestamptz
    required: true
  active:
    type: Integer
    required: true


film:
  film_id:
    type: Integer
    required: true
  title:
    type: String
    required: true
  description:
    type: String
    required: false
  release_year:
    type: Integer
    required: false
  language_id:
    type: Integer
    required: true
  original_language_id:
    type: Integer
    required: false
  rental_duration:
    type: Integer
    required: true
  rental_rate:
    type: Float
    required: true
  length:
    type: Integer
    required: false
  replacement_cost:
    type: Float
    required: true
  rating:
    type: String
    required: false
  last_update:
    type: Timestamp
    required: true
    parse:
      - Replace("-", "/")
      - Regex_replace(" \d{2}:\d{2}:\d{2}\.\d+\+\d{2}", "") 
  special_features:
    type: String
    required: false
  fulltext:
    type: String
    required: false
