category:
  category_id:
    type: number
    required: true
    parse:
      - Replace(",", ".")
      - ToFloat(2)
  name:
    type: string
    required: false
  last_update:
    type: string
    required: true
    parse:
      - Replace('-', '/')
      - Regex_replace(" \d{2}:\d{2}:\d{2}\+\d{2}", "")
